# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/SEP/Zybo-Z7-Master.xdc

# Block Designs: bd/RNGCore_imp/RNGCore_imp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RNGCore_imp || ORIG_REF_NAME==RNGCore_imp} -quiet] -quiet

# IP: bd/RNGCore_imp/ip/RNGCore_imp_Debouncer_0_0/RNGCore_imp_Debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RNGCore_imp_Debouncer_0_0 || ORIG_REF_NAME==RNGCore_imp_Debouncer_0_0} -quiet] -quiet

# IP: bd/RNGCore_imp/ip/RNGCore_imp_Debouncer_0_1/RNGCore_imp_Debouncer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RNGCore_imp_Debouncer_0_1 || ORIG_REF_NAME==RNGCore_imp_Debouncer_0_1} -quiet] -quiet

# IP: bd/RNGCore_imp/ip/RNGCore_imp_ClockDivider_0_0/RNGCore_imp_ClockDivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RNGCore_imp_ClockDivider_0_0 || ORIG_REF_NAME==RNGCore_imp_ClockDivider_0_0} -quiet] -quiet

# IP: bd/RNGCore_imp/ip/RNGCore_imp_RNGCore_0_1/RNGCore_imp_RNGCore_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RNGCore_imp_RNGCore_0_1 || ORIG_REF_NAME==RNGCore_imp_RNGCore_0_1} -quiet] -quiet

# XDC: bd/RNGCore_imp/RNGCore_imp_ooc.xdc
